export const SITTERS = [
  {
    id: 'sarah-b',
    name: 'Sarah B.',
    last: 'Bennett',
    city: 'Austin, TX',
    rating: 4.7,
    reviews: 45,
    expert: ['Active Dogs', 'Senior Pets'],
    services: ['Dog Walking', 'Cat Sitting', 'Overnight Stays'],
    bio: 'Passionate dog lover with 10+ years of experience caring for active pups and gentle seniors. I treat every visit like a playdate — long walks, belly rubs, and detailed photo updates so you never miss a moment.',
    petType: 'dog',
    color: '#FCD9A1',
    accent: '#F37A3E',
    yearsActive: 6,
    repeatClients: 38,
    response: '< 1 hr',
    rate: '$28/hr',
    available: 'This weekend',
    monogram: 'SB'
  },
  {
    id: 'mike-l',
    name: 'Mike L.',
    last: 'Lin',
    city: 'San Francisco, CA',
    rating: 4.5,
    reviews: 30,
    expert: ['Indoor Cats', 'Small Animals'],
    services: ['Cat Sitting', 'Drop-in Visits', 'Bunny Boarding'],
    bio: 'Cat whisperer and small-mammal specialist. Quiet households, slow introductions, and a calm hand — perfect for shy kitties and skittish rabbits.',
    petType: 'cat',
    color: '#F4B8C7',
    accent: '#D87680',
    yearsActive: 4,
    repeatClients: 22,
    response: '< 2 hr',
    rate: '$24/hr',
    available: 'Tomorrow',
    monogram: 'ML'
  },
  {
    id: 'chloe-p',
    name: 'Chloe P.',
    last: 'Park',
    city: 'Denver, CO',
    rating: 4.9,
    reviews: 52,
    expert: ['Puppies', 'Multiple Pets'],
    services: ['Puppy Training', 'Pack Walks', 'Daycare'],
    bio: 'Certified trainer who loves chaotic puppy energy. Multi-pet households are my happy place — I keep everyone enriched, exercised, and on schedule.',
    petType: 'dog',
    color: '#FCE7A5',
    accent: '#E0A800',
    yearsActive: 5,
    repeatClients: 41,
    response: '< 30 min',
    rate: '$32/hr',
    available: 'Today',
    monogram: 'CP'
  },
  {
    id: 'james-r',
    name: 'James R.',
    last: 'Rivera',
    city: 'Seattle, WA',
    rating: 4.8,
    reviews: 67,
    expert: ['Reactive Dogs', 'Anxious Pets'],
    services: ['Solo Walks', 'Behavior Support', 'Overnight Stays'],
    bio: 'Force-free trainer with a soft spot for reactive rescues. Patient pace, predictable routines, and decompression first.',
    petType: 'dog',
    color: '#B8DCB0',
    accent: '#5BA34A',
    yearsActive: 8,
    repeatClients: 55,
    response: '< 1 hr',
    rate: '$35/hr',
    available: 'Next week',
    monogram: 'JR'
  },
  {
    id: 'priya-k',
    name: 'Priya K.',
    last: 'Kapoor',
    city: 'Brooklyn, NY',
    rating: 5.0,
    reviews: 28,
    expert: ['Exotic Pets', 'Reptiles'],
    services: ['Drop-in Visits', 'Vacation Care', 'Feeding'],
    bio: 'Herp vet tech by day, exotic sitter by evening. Bearded dragons, geckos, parrots — I speak their language.',
    petType: 'exotic',
    color: '#C8E0F4',
    accent: '#5A8FD0',
    yearsActive: 3,
    repeatClients: 18,
    response: '< 2 hr',
    rate: '$30/hr',
    available: 'This week',
    monogram: 'PK'
  },
  {
    id: 'devon-w',
    name: 'Devon W.',
    last: 'Wells',
    city: 'Portland, OR',
    rating: 4.6,
    reviews: 39,
    expert: ['Large Breeds', 'Senior Dogs'],
    services: ['Long Walks', 'Hiking Adventures', 'Medication Care'],
    bio: 'Big-dog enthusiast and licensed CPR pet first-aider. I have the harnesses, the trails, and the patience for slow senior strolls.',
    petType: 'dog',
    color: '#F9CFA8',
    accent: '#C46B2C',
    yearsActive: 7,
    repeatClients: 33,
    response: '< 3 hr',
    rate: '$30/hr',
    available: 'This weekend',
    monogram: 'DW'
  },
  {
    id: 'aiko-t',
    name: 'Aiko T.',
    last: 'Tanaka',
    city: 'Los Angeles, CA',
    rating: 4.8,
    reviews: 71,
    expert: ['Multi-Cat Homes', 'Medication'],
    services: ['Cat Sitting', 'Drop-in Visits', 'Vet Transport'],
    bio: 'Cat-only sitter for 9 years. Litter-box detective, pill-pocket pro, and absolute sucker for elderly tuxedos.',
    petType: 'cat',
    color: '#E5C9F2',
    accent: '#9669C2',
    yearsActive: 9,
    repeatClients: 62,
    response: '< 1 hr',
    rate: '$26/hr',
    available: 'Today',
    monogram: 'AT'
  },
  {
    id: 'noah-g',
    name: 'Noah G.',
    last: 'Garcia',
    city: 'Miami, FL',
    rating: 4.7,
    reviews: 43,
    expert: ['Water-Loving Dogs', 'Puppies'],
    services: ['Beach Walks', 'Puppy Visits', 'Daycare'],
    bio: 'Beach-day enthusiast. If your pup loves saltwater and sandy zoomies, we’ll be best friends by sunset.',
    petType: 'dog',
    color: '#A8E0E4',
    accent: '#3FA0A6',
    yearsActive: 4,
    repeatClients: 28,
    response: '< 1 hr',
    rate: '$27/hr',
    available: 'This weekend',
    monogram: 'NG'
  }
];

export const PET_TYPES = ['All Pets', 'Dogs', 'Cats', 'Rabbits', 'Birds', 'Reptiles'];
